# Generated by Django 2.2.16 on 2022-03-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date', '-pk')},
        ),
    ]
