# Generated by Django 2.2.16 on 2022-04-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220404_1756'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_user_follower_user',
        ),
    ]
